[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader"

[deploy]
startCommand = "vendor/bin/heroku-php-apache2 public/"
healthcheckPath = "/"
healthcheckTimeout = 100 