[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT public/index.php"
healthcheckPath = "/"
healthcheckTimeout = 100 